---
- name: Enable S3 sleep
  block:
    - name: Check if Sleep is configured in the boot command
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="((?:(?!mem_sleep_default=\w*).)*?)"$'
        backup: true
        state: absent
      check_mode: true
      register: grub_cmdline_check_mem_sleep_default
      changed_when: false

    - name: Insert Sleep config if missing
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*?)\"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 mem_sleep_default=deep"'
        backup: true
        backrefs: true
        state: present
      when: grub_cmdline_check_mem_sleep_default.found > 0
      notify: Update Grub

    - name: Update Sleep config if needed
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '(.*)mem_sleep_default=\w*(.*)$'
        replace: '\1mem_sleep_default=deep\2'
        backup: true
      when: grub_cmdline_check_mem_sleep_default.found == 0
      notify: Update Grub
