---
- name: HW settings
  block:
    - name: Use Dell Laptop SMM BIOS hwmon driver and disable psmouse
      ansible.builtin.template:
        src: dell.conf.j2
        dest: /etc/modprobe.d/dell.conf
        owner: "root"
        group: "root"
        mode: '0644'
      notify: Update initramfs

    - name: Settings for i915
      ansible.builtin.template:
        src: i915.conf.j2
        dest: /etc/modprobe.d/i915.conf
        owner: "root"
        group: "root"
        mode: '0644'
      notify: Update initramfs

    - name: Configuring VA-API Driver
      ansible.builtin.template:
        src: libva_ihd.sh.j2
        dest: /etc/profile.d/libva_ihd.sh
        owner: "root"
        group: "root"
        mode: '0644'
      notify: Apply changes to etc_profile directly

    - name: Headphones Hissing
      ansible.builtin.template:
        src: headphones_hissing.service.j2
        dest: /etc/systemd/user/headphones_hissing.service
        owner: "root"
        group: "root"
        mode: '0644'
