---
- name: Enable S3 sleep
  ansible.builtin.include_tasks: enable_s3_sleep.yml

- name: Prevent some hangs
  ansible.builtin.include_tasks: prevent_some_hangs.yml

- name: Internal microphone
  ansible.builtin.include_tasks: internal_microphone.yml

- name: Improve CPU performance
  ansible.builtin.include_tasks: improve_cpu_performance.yml

- name: Enable ACPI Linux support
  ansible.builtin.include_tasks: enable_acpi_linux_support.yml

- name: HW settings
  ansible.builtin.include_tasks: hw_settings.yml

- name: Autorotate display
  ansible.builtin.include_tasks: autorotate_display.yml

- name: Workaround throttling issue
  ansible.builtin.include_tasks: workaround_throttling_issue.yml
