---
- name: Install Block
  block:
    - name: Install
      ansible.builtin.package:
        name:
          - snapd
          - gnome-software-plugin-snap
        state: present

    - name: Remove old revisions on weekly basis
      become: true
      ansible.builtin.template:
        src: "snap_remove_old_revisions.sh.j2"
        dest: "/etc/cron.weekly/snap_remove_old_revisions.sh"
        owner: "root"
        group: "root"
        mode: '0755'
