---
- name: Install Block
  block:
    - name: Check if Scheduler is configured in the boot command
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=\".*?((?:(elevator=\w*))).*?\"$'
        backup: true
        state: absent
      check_mode: true
      register: grub_cmdline_check_scheduler
      changed_when: false

    - name: Insert Scheduler config if missing
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=\"(.*?)\"$'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 elevator=deadline"'
        backup: true
        backrefs: true
        state: present
      when: grub_cmdline_check_scheduler.found == 0
      notify: Update Grub

    - name: Update Scheduler config if needed
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '(.*)elevator=\w*(.*)$'
        replace: '\1elevator=deadline\2'
        backup: true
      when: grub_cmdline_check_scheduler.found >= 0
      notify: Update Grub

    - name: Flush Handlers
      ansible.builtin.meta: flush_handlers
