---
# - name: Install Block
#   block:
      - name: Install DisplayCAL
        become: true
        community.general.flatpak:
          name: net.displaycal.DisplayCAL
          state: present

      - name: Create Color Profile dir on remote host if it does not exist
        become: true
        ansible.builtin.file:
          path: "/usr/local/argyllcms"
          state: directory
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"
          mode: '0755'

      - name: Check if Color Profile is present
        ansible.builtin.stat:
          path: "/usr/share/color/icc/DisplayA.icc"
        register: color_profile_file

      - name: Show hint how to create config file
        ansible.builtin.debug:
          msg: "No color profile found. Please create one and copy to /usr/share/color/icc/DisplayA.icc"
        changed_when: not color_profile_file.stat.exists
        when: not color_profile_file.stat.exists and monitor_color_profiling.load_on_startup | bool

      - name: Script to set Color Profile
        become: true
        ansible.builtin.template:
          src: "set_icc.j2"
          dest: "/usr/local/argyllcms/set_icc"
          owner: "root"
          group: "root"
          mode: '0644'
        when: color_profile_file.stat.exists and monitor_color_profiling.load_on_startup | bool

      - name: Autostart-Entry for all Users
        become: true
        ansible.builtin.template:
          src: "icc-profile-loading.desktop.j2"
          dest: "/etc/xdg/autostart/icc-profile-loading.desktop"
          owner: "root"
          group: "root"
          mode: '0644'
        when: color_profile_file.stat.exists and monitor_color_profiling.load_on_startup | bool
