---
- name: Check disk space
  block:
    # - name: get disk usage
    #   command: df -h
    #   register: disk_usage
    - name: Check disk space available
      ansible.builtin.shell: df -h / | awk 'NR==2 {print $5}'
      changed_when: disk_usage.stdout[:-1]|int > 90
      register: disk_usage

    - name: Print disk usage if above 90 %
      ansible.builtin.debug:
        msg: Disk space on {{ inventory_hostname }} is {{ disk_usage.stdout[:-1] | int }} %
      when: disk_usage.stdout[:-1]|int > 90

#    - name: Send discord message when disk space is over 90%
#      uri:
#        url: "{{ discord_webhook_url }}"
#        method: POST
#        body_format: json
#        body: '{"content": "Disk space on {{ inventory_hostname }} is above 90%!"}'
#        headers:
#          Content-Type: application/json
#        status_code: 204
#      when: disk_usage.stdout[:-1]|int > 90
