---
- name: Prevent Suspending When Laptop Lid is Closed
  block:

    - name: Create Drop In Config dir on remote host if it does not exist
      become: true
      ansible.builtin.file:
        path: "/etc/systemd/logind.conf.d"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Prevent Suspending When Laptop Lid is Closed
      become: true
      ansible.builtin.template:
        src: "LidSwitch.j2"
        dest: "/etc/systemd/logind.conf.d/90-LidSwitch.conf"
        owner: "root"
        group: "root"
        mode: '0644'
