---
- name: Install Block
  block:
    - name: Install Dev Tools
      ansible.builtin.package:
        name:
          - git
          - meld
          - binwalk
          - python3
          - python3-bashate
          - build-essential
          - ca-certificates-java
        state: present

    - name: Install shellcheck
      community.general.snap:
        name: shellcheck
        state: present

    - name: Install shfmt - A shell parser, formatter and interpreter
      community.general.snap:
        name: shfmt
        state: present
